fix run script to fail when build fails

diff --git a/run b/run
--- a/run
+++ b/run
@@ -59,6 +59,15 @@ if [ "$type" = "test" ] || [ "$type" = "dev" ] || [ "$type" = "check" ]
         failed_services=$(echo "${output}" | grep "exited with code" | grep -v "exited with code 0")
         failed_services_count=$(echo "${failed_services}" | grep . | wc -l)
 
+        failed_to_build=$(echo "${output}" | grep "failed to build")
+        failed_to_build_count=$(echo "${failed_to_build}" | grep . | wc -l)
+        if [ $failed_to_build_count -ne 0 ]; then
+            echo ""
+            echo ""
+            echo "Build failed."
+            exit 1
+        fi
+
         if [ $failed_services_count -ne 0 ]; then
             printf "${failed_services}"
             echo ""
