build fails if tests fail

diff --git a/run b/run
--- a/run
+++ b/run
@@ -6,6 +6,10 @@ as_arguments=$(printf " -f %s" "${docker_compose_files[@]}")
 exec 5>&1
 output=$(docker-compose $as_arguments up --build | tee >(cat - >&5))
 
-did_fail=$(echo "${output}" | grep "exited with code" | grep -v "exited with code 0" | wc -l)
+failed_services=$(echo "${output}" | grep "exited with code" | grep -v "exited with code 0")
+failed_services_count=$(echo "${failed_services}" | wc -l)
 
-exit ${did_fail}
+if [ $failed_services_count -ne 0 ]; then
+    echo "\n\n${failed_services}"
+    exit 1
+fi
